app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

book_profile:
    path: /book/{id}
    defaults: {_controller: AppBundle:Libro:show}
book_list:
    path: /book
    defaults: {_controller: AppBundle:Libro:showList}

people_list:
    path: /people
    defaults: {_controller: AppBundle:Usuario:showList}