AppBundle\Entity\Usuario:
    type: entity
    table: usuario
    uniqueConstraints:
        UNIQ_2265B05D92FC23A8:
            columns:
                - username_canonical
        UNIQ_2265B05DA0D96FBF:
            columns:
                - email_canonical
        UNIQ_2265B05DC05FB297:
            columns:
                - confirmation_token
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        pathFoto:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: path_foto
        bio:
            type: string
            nullable: true
            length: 140
            options:
                fixed: false
    lifecycleCallbacks: {  }
