easy_admin:
    site_name: BookSite
    entities:
        Usuarios:
            class: AppBundle\Entity\Usuario
            form:
                fields:
                    - username
                    - email
                    - pathFoto
                    - bio
                    - { property: 'plainPassword', type: 'password', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

        Libros:
            class: AppBundle\Entity\Libro
            form:
                fields:
                    - isbn
                    - titulo
                    - autor
                    - editorial
                    - pathImagen
                    - paginas
                    - puntuacion

